##############################################################################
# Copyright (C) 2021, Nordix Foundation
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: tgen-tapp-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: tgen-tapp-sa-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: tgen-tapp-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tgen-tapp
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tgen-tapp-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tgen-tapp
subjects:
- kind: ServiceAccount
  name: tgen-tapp-sa
  namespace: default
