##############################################################################
# Copyright (C) 2021, Nordix Foundation
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgen-tapp-c-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgen-tapp-c
  template:
    metadata:
      labels:
        app: tgen-tapp-c
        app-instance: tgen-tapp-c-deployment
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            {
              "name": "test-net",
              "ips": ["10.10.10.3/24"]
            }
        ]'
    spec:
      serviceAccount: tgen-tapp-sa
      containers:
      - name: tgen-tapp-pod-container-c
        image: tgen-tapp:latest
        imagePullPolicy: IfNotPresent
        command:
        - tgenapp
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tgen-tapp-c
  name: tgen-tapp-c-headless-service
spec:
  clusterIP: None  # headless service
  selector:
    app-instance: tgen-tapp-c-deployment
  ports:
    - port: 8890
      targetPort: 8890
      name: udp
      protocol: UDP
