---
apiVersion: v1
kind: Pod
metadata:
  name: tgen-tapp-pod-a
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "test-net",
          "ips": ["10.10.10.1/24"]
        }
    ]'
spec:
  serviceAccount: tgen-tapp-sa
  containers:
  - name: tgen-tapp-pod-container-a
    image: tgen-tapp:latest
    imagePullPolicy: IfNotPresent
    command:
    - tgenapp
    args:
    - -readbufsize=9000
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
