##############################################################################
# Copyright (C) 2021, Nordix Foundation
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgen-tapp-d-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tgen-tapp-d
  template:
    metadata:
      labels:
        app: tgen-tapp-d
        app-instance: tgen-tapp-d-deployment
    spec:
      serviceAccount: tgen-tapp-sa
      containers:
      - name: tgen-tapp-pod-container-d
        image: tgen-tapp:latest
        imagePullPolicy: IfNotPresent
        command:
        - tgenapp
        args:
        - -readbufsize=1000
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tgen-tapp-d
  name: tgen-tapp-d-clusterip-service
spec:
  type: ClusterIP
  selector:
    app-instance: tgen-tapp-d-deployment
  ports:
    - port: 8890
      targetPort: 8890
      name: udp
      protocol: UDP
