# Copyright (c) 2021 Ericsson Software Technology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: Pod
metadata:
  name: tgen-tapp-pod-b
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "test-net",
          "ips": ["10.10.10.2/24"]
        }
    ]'
spec:
  serviceAccount: tgen-tapp-sa
  containers:
  - name: tgen-tapp-pod-container-b
    image: tgen-tapp:latest
    imagePullPolicy: IfNotPresent
    command:
    - tgenapp
    args:
    - -readbufsize=9000
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace